name: Verify
on:
  pull_request:
    branches: [ master ]

jobs:
  verify:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x, 26.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Lint, Test, And Coverage
      run: npm run lint && npm run test:cover
    - name: Coverage Upload
      if: ${{ success() }}
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./reports/coverage/lcov.info
